### ISSUE TITLE
standardize project name references across files

### ISSUE THREAD

**Issue by twardnw** [amazeeio/drupal-example-simple#15]
To allow for an easier time to find/replace the project name, a standard form should be chosen. There are currently a few different methods used:

https://github.com/amazeeio/drupal-example-simple/blob/c669682c15d5d0249248b7360b7f965b2a8df9f2/.env#L2

https://github.com/amazeeio/drupal-example-simple/blob/main/.lagoon.yml#L3

https://github.com/amazeeio/drupal-example-simple/blob/c669682c15d5d0249248b7360b7f965b2a8df9f2/docker-compose.yml#L5

https://github.com/amazeeio/drupal-example-simple/blob/c669682c15d5d0249248b7360b7f965b2a8df9f2/docker-compose.yml#L18

Also several references to a completely wrong repo name, `drupal-simple-example`, in the README (can't permalink to specific lines in a markdown file)

**Comment by tobybellwood** [comment]
ah - yes, there is some legacy stuff in there.  Will pick these up and clean out. :100:
