### ISSUE TITLE
Getting error when trying to install using drupal 9 example

### ISSUE THREAD

**Issue by manojbisht891** [amazeeio/drupal-example-simple#157]
I am getting error, when trying to install lagoon drupal 9 or drupal 8 example. I am installing it with pygmy.

Error:
 => ERROR [drupal8-example-simple_nginx internal] load metadata for docker.io/library/drupal8-example-simple-cli:latest 

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

Steps Followed:
1. Clone the drupal 9 example repo
2. Done pygmy up
3. docker-compose build && docker-compose up -d

**Comment by ArloL** [comment]
Try `docker-compose build cli` on it's own first. That worked for me.
