### ISSUE TITLE
Move to PHP 8.0

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/drupal-example-simple#243]
Also has Composer 2, which is a far better starting point for most people.

**Comment by tobybellwood** [comment]
Check out https://github.com/lagoon-examples/drupal9-base - we're gradually transitioning across there

**Comment by seanhamlin** [comment]
TIL, thanks Toby.

**Comment by tobybellwood** [comment]
yup - it's all still in motion - but this multi-branch repo is pretty confusing!
