### ISSUE TITLE
Redis 5 does not return PONG by default

### ISSUE THREAD

**Issue by twerthmueller** [amazeeio/drupal-example-simple#342]
Hi

In your Redis integration, there exists a problem with Redis 5, because Redis does not return the string 'PONG' as a success message anymore.

![2022-07-13 10-23-48](https://user-images.githubusercontent.com/6920143/178686893-7dd03e7b-ebdd-4a58-8589-883c0ea4a112.png)

https://github.com/amazeeio/drupal-example-simple/blob/1aef5aa8d44f7026146611a927fa292c87b39c4d/assets/all.settings.php#L75

We should check the response in an other way:

```
$response = $redis->ping('PONG');
if (strpos($response, 'PONG') === false) {
   throw new \Exception('Redis could be reached but is not responding correctly.');
}

```

or 

```
$response = $redis->ping();
if (!$response) {
   throw new \Exception('Redis could be reached but is not responding correctly.');
}
```

Currently it's possible, that many of your running Lagoon environments uses the fallback on redis-unavailable.services.yml and does not use any cache, when Redis should be enabled. 

Would also nice, when the Lagoon documentation gets updated: https://docs.lagoon.sh/drupal/services/redis/

Thanks,
Thomas

**Comment by twerthmueller** [comment]
From the Redis documentation:
![2022-07-13 10-37-34](https://user-images.githubusercontent.com/6920143/178689589-2a1218d6-a6e7-4225-9190-a2ca7c581ab1.png)

https://github.com/phpredis/phpredis/tree/5.3.4#ping

**Comment by tobybellwood** [comment]
Thanks, @twerthmueller - hopefully this won't catch too many people. I've updated this example, but am currently making an all-new PHP8-based one, so will ensure that works from the get-go.
